server:
  port: 8088
spring:
  application:
    name: user-register
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: false