server:
  port: 8888
spring:
  application:
    name: zuul-server
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
zuul:
  routes:
    user-register:
      path: /userRegister/**
      service-id: user-register
    user-valid:
      path: /userValid/**
      service-id: user-valid
    email-server:
      path: /emailServer/**
      service-id: email-server